easy_admin:
    entities:
        Brand:
            class: PhoneBundle\Entity\Brand
            list:
                fields:
                    - id
                    - name
                    - model
                    - products
            show:
                fields:
                    - name
                    - model
                    - products
            form:
                fields:
                    - name
                    - model
                    - products

