easy_admin:
    entities:
        Brand:
            class: PhoneBundle\Entity\Brand
            list:
                fields:
                    - id
                    - name
                    - category
            show:
                fields:
                    - name
                    - category
            form:
                fields:
                    - name
                    - category

