easy_admin:
    entities:
        Category:
            class: PhoneBundle\Entity\Category
            form:
                fields:
                    - name
                    - model
                    - brand
