easy_admin:
    entities:
        Category:
            class: PhoneBundle\Entity\Category
            list:
                fields:
                    - brand
                    - name
                    - model
            form:
                fields:
                    - brand
                    - name
                    - model
