<?php

namespace PhoneBundle\Repository;

/**
 * PhoneUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneUserRepository extends \Doctrine\ORM\EntityRepository
{
}
